### PR TITLE
Emitter should not write trailing spaces

### PR DESCRIPTION
**Pull request by bomgar**

### CODE REVIEW

**Comment by bomgar** [comment]
should fix https://github.com/chyh1990/yaml-rust/issues/47

**Comment by bomgar** [comment]
@dtolnay this project seems dead. Could you confirm this? Is it because nobody wants to do the work?

**Comment by hoodie** [comment]
@bomgar I certainly hope it's not dead. @chyh1990 if have too little time or resources to review PRs, perhaps you could add others to the list of contributors?

**Comment by iredelmeier** [comment]
@bomgar thanks for getting this started! Looks like arrays and empty hash maps still had the trailing spaces, so I pushed #66.

**Comment by bomgar** [comment]
@iredelmeier I close this one. You seem to have the better version. I fear that the maintainer is not watching this either way.

**Pull request closed without merging**
