### PR TITLE
Parser: Do not clone on peeking

### PR DESCRIPTION
**Pull request by chris-m-h**
This eliminates calls to clone() and to_owned() in the parser

- Peeking now returns reference only
- To obtain value, fetch_token needs to be called
- The parser was adapted accordingly
- Also: Pass anchor name by value to register_anchor

### CODE REVIEW

**Comment by hoodie** [comment]
I'd really like to see how much this impacts performance

**Comment by chris-m-h** [comment]
Using twitter.json from the JSON benchmark (http://json.rs/) I got the following bench results:

- For a parser with an EventReceiver that simply ignores the events, I got a performance gain of 22%.
- Including the creation of the YAML struct, I still got a performance gain of 15%.

I would regard that quite a difference, although I have to admit that it is less than I expected... I do not claim that the tests were performed under experimental conditions...

**Comment by chris-m-h** [comment]
Any interest in this, @dtolnay or @chyh1990 ? Basically, just the internal structure of the parser functions had to be changed to stay inside the lifetime of the token references, in this way avoiding the need for cloning.

**Comment by chyh1990** [comment]
+1. Looks good to me. But it is a large patch, can we get another reviewer for it? @dtolnay

**Pull request merged**
