### PR TITLE
implemented ToString

### PR DESCRIPTION
**Pull request by hoodie**
Hey there, I implemented `Yaml::to_string()` and `From<&Yaml> for String`.
I know it's a bit of a duplication of `YamlEmitter`, but I found this more accessible.

cheers

### CODE REVIEW

**Comment by hoodie** [comment]
Hi again, what is your opinion on this PR? It doesn't build on Rust 1.0.0 and 1.1.0, but it builds on stable. Perhaps you would consider changing the travis configuration?

**Comment by chyh1990** [comment]
er...maybe we should implement this in more efficient way with a string buffer, to avoid String allocations?

**Comment by hoodie** [comment]
You probably refer to the `Array` and `Hash` cases, what would a string buffer be? `write!()` ?
I actually don't have that in [here](https://github.com/hoodie/concatenation_benchmarks-rs) yet, but I can do that and come back you.
Though I assume that this is quite fast already.

**Comment by hoodie** [comment]
What do you say?

**Comment by hoodie** [comment]
no longer necessary, #32 is more important :D

**Pull request closed without merging**
