### PR TITLE
fixed: emitter also emits complex keys

### PR DESCRIPTION
**Pull request by hoodie**
Hey, I was playing around with the `YamlEmitter` and noticed that it did not yet support complex hashmap key and instead returned an `Error`. With this PR I'm trying to introduce this functionality, please give it a try.

Thank you very much

### CODE REVIEW

**Comment by chyh1990** [comment]
Complex key is rarely used, can you provide any unit tests with your implementation? :-)

**Comment by hoodie** [comment]
You're right, I'm sorry - I'll check them in right away.

**Comment by hoodie** [comment]
hey? what do you think of this PR? anything you still want me to improve?

**Comment by hoodie** [comment]
Hi @chyh1990, could you perhaps review this PR? I'd love to see this in `0.3.5`
Thank you

**Comment by hoodie** [comment]
Thank you very much 👍 👍

**Pull request merged**
